### ISSUE TITLE
not bustafunk compatible?

### ISSUE THREAD

**Issue by peterquest** [thebareju/sos-project#1]
Hi i just want this to play through the pfunk speakers. in all fairness i haven't tried very hard to get it to work. i apt-got chuck, libsndfile, and pip installed all the necessaries. 

trying to start `chuck -s demo.ck` produces: 

`[demo.ck]:line(72): undefined type 'OscRecv'...Segmentation fault (core dumped)`

oh nooooo

**Comment by peterquest** [comment]
whoa jk i compiled chuck from src instead of using apt-get and now it works. 

it's totally sick. does it just run forever?

**Comment by peterquest** [comment]
btw i'm totally messing with this this weekend and submitting a pull request for various modes of handling syllables and pieces of randomness. or maybe percussive special characters. (commas, periods, semicolons)

does that count as cheating for your project? :8ball:

**Comment by garden-nomes** [comment]
Go for it!  And write some project updates for Sherri while you're at it?
